CREATE database ZEPTO_SQL_PROJECT;
USE ZEPTO_SQL_PROJECT;

DROP TABLE IF EXISTS ZEPTO;
CREATE TABLE ZEPTO_V2(
SERIAL_NO  SERIAL PRIMARY KEY,
CATEGORY VARCHAR(120),
NAME VARCHAR(150) NOT NULL,
MRP NUMERIC (8,2),
DISCOUNTPERCENT NUMERIC(5,2),
AVAILABLEQUANTITY INTEGER,
DISCOUNTEDSELLINGPRICE NUMERIC(8,2),
WEIGHTINGMS INTEGER,
OUTOFSTOCK BOOLEAN,
QUANTITY INTEGER
);

-- DATA EXPLORATION --

SELECT COUNT(*) FROM ZEPTO_V2;


ALTER TABLE ZEPTO_V2
DROP COLUMN SERIAL_NO;
SHOW TABLES;

ALTER TABLE ZEPTO_V2
ADD COLUMN SERIAL_NO INT FIRST;

ALTER TABLE ZEPTO_V2
MODIFY COLUMN SERIAL_NO INT auto_increment PRIMARY KEY;


-- DATA EXPLORATION -- 
-- VIEW FEW RECORDS --
SELECT * FROM ZEPTO_V2 
LIMIT 10;

-- COUNT TOTAL PRODUCTS
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM ZEPTO_V2;

-- DIFFERENT PRODUCT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO_V2
ORDER BY CATEGORY;


-- FIND MISSING OR NULL VALUES
SELECT 
	SUM(CASE WHEN MRP IS NULL THEN 1 ELSE 0 END) AS MISSING_MRP,
    SUM(CASE WHEN DISCOUNTPERCENT IS NULL THEN 1 ELSE 0 END) AS MISSING_DP,
    SUM(CASE WHEN AVAILABLEQUANTITY IS NULL THEN 1 ELSE 0 END) AS MISSING_QTY
FROM ZEPTO_V2;

-- PRODUCT OUT OF STOCK VS IN STOCK
SELECT OUTOFSTOCK, COUNT(SERIAL_NO)
FROM ZEPTO_V2
GROUP BY OUTOFSTOCK;
SELECT * FROM ZEPTO_V2;

--  PRODUCT NAME MULTIPLE TIMES
SELECT NAME, COUNT(SERIAL_NO) AS NO_OF_TIMES
FROM ZEPTO_V2
GROUP BY NAME
HAVING COUNT(SERIAL_NO) > 1
ORDER BY COUNT(SERIAL_NO) DESC;


-- 2 DATA CLEANING
-- PRODUCT MRP 0
SELECT * FROM ZEPTO_V2
WHERE MRP = 0 
OR DISCOUNTEDSELLINGPRICE = 0;

DELETE FROM ZEPTO_V2
WHERE MRP = 0;

SET SQL_SAFE_UPDATES = 0;

-- CONVERT PAISE INTO RUPEES
UPDATE ZEPTO_V2
SET MRP = MRP/100.0,
DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE/100.0;


-- Q1. Find the top-best value products based on the discount percentage
SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO_V2
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;


-- Q2. What are the products with high MRP but out of stock
SELECT DISTINCT NAME, MRP
FROM ZEPTO_V2
WHERE OUTOFSTOCK = TRUE AND MRP > 300
ORDER BY MRP DESC;

-- Q3. Calculate estimated revenue for each category
SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;


-- Q4. Find all products where MRP is greater then 500 and discount is less than 10%
SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO_V2
WHERE MRP > 500 AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC, DISCOUNTPERCENT DESC;

-- Q5. Identify the top 5 categories offering the highest avg discount percentage
SELECT DISTINCT CATEGORY, ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DIS_PER
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY AVG_DIS_PER DESC
LIMIT 5;
-- Q6. Find the price per gram for products above 100g and sort by best values
SELECT DISTINCT NAME, DISCOUNTEDSELLINGPRICE, WEIGHTINGMS, 
ROUND(DISCOUNTEDSELLINGPRICE/WEIGHTINGMS,2) AS PRICE_PER_GMS
FROM ZEPTO_V2
WHERE WEIGHTINGMS >=  100
ORDER BY PRICE_PER_GMS;
-- Q7. Group the products into categories like low, medium, bulk

SELECT DISTINCT NAME, WEIGHTINGMS, 
CASE WHEN WEIGHTINGMS < 1000 THEN 'LOW'
	WHEN WEIGHTINGMS < 5000  THEN 'MEDIUM'
ELSE 'BULK'
END AS WEIGHT_CATEGORY
FROM ZEPTO_V2;

-- Q8. What is the total inventory weight per category
SELECT CATEGORY, SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;









